image: fedora:latest

generaltester:
  script:
  - dnf install -y python3-pip python3-devel diffutils ncurses
  - pip3 install mypy black
  - bash grade.sh
  timeout: 2 hours 30 minutes
  artifacts:
    when: always
    paths:
      - results.txt
    expire_in: 1 month
